server:
  port: 8071
  tomcat:
    max-http-header-size: 16KB
    relaxed-path-chars: |
      \
    relaxed-query-chars: |
      \
spring:
  application:
    name: LLMentorLearn_langchain4j

langchain4j:
  open-ai:
    chat-model:
      api-key: @dashscope.api.key@
      model-name: qwen-max-latest
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: @dashscope.api.key@
      model-name: qwen-max-latest
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.ai: DEBUG          # Spring AI 详细日志（关键）
    org.apache.tomcat: INFO
    org.springframework.web: DEBUG           # 打印请求路径、参数
    org.springframework.web.servlet: DEBUG   # 打印 MVC 详细流程


