spring:
  application:
    name: LLMentorLearn_SpringAI
  ai:
    openai:
      api-key: sk-1e03ea92532b4ca4a8a74d91858d35fa
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
server:
  port: 8062
