spring:
  application:
    name: LLMentorLearn_RAG
  ai:
    dashscope: # 大模型配置
      api-key: @dashscope.api.key@
      model: qwen-plus
      embedding: # embedding（向量化配置）
        options:
          model: text-embedding-v4 # 向量模型
          dimensions: 768  # 向量维度（几维向量）
    # 向量数据库配置
    vectorstore: # 向量数据库配置
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 768
        max-document-batch-size: 9
        initialize-schema: true
        table-name: multimodal_st
        # table-name: vector_st
        # special_equipment_st

    # pgvector数据库数据源配置
  datasource: # 数据源配置
    url: jdbc:postgresql://192.168.43.54:5433/rag_test # 记得改成你自己的
    #    url: jdbc:postgresql://192.168.0.121:5433/rag_test # 记得改成你自己的
    username: pgvector # 记得改成你自己的
    password: pgvector666 # 记得改成你自己的
    # elasticsearch 数据库配置
  elasticsearch:
    uris: http://192.168.43.54:9200
    #    uris: http://192.168.0.121:9200
    # neo4j 数据库配置
  neo4j:
    uri: bolt://192.168.43.54:7687
    #    uri: bolt://192.168.0.121:7687
    authentication:
      username: neo4j
      password: neo4j666

minio:
  url: http://192.168.43.54:9000 # 记得改成你自己的
  #  url: http://192.168.0.121:9000 # 记得改成你自己的
  accessKey: minioadmin # 记得改成你自己的
  secretKey: minioadmin # 记得改成你自己的
  bucketName: rag-test # 记得改成你自己的
  endpoint: http://192.168.43.54:9000 # 记得改成你自己的
#  endpoint: http://192.168.0.121:9000 # 记得改成你自己的

server:
  port: 8072
  tomcat:
    max-http-header-size: 16KB
    relaxed-path-chars: |
      \
    relaxed-query-chars: |
      \  

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.ai: DEBUG          # Spring AI 详细日志（关键）
    org.apache.tomcat: INFO
    org.springframework.web: DEBUG           # 打印请求路径、参数
    org.springframework.web.servlet: DEBUG   # 打印 MVC 详细流程


