server:
  port: 8073
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    max-http-header-size: 16KB
    relaxed-path-chars: |
      \
    relaxed-query-chars: |
      \  

spring:
  main:
    web-application-type: reactive
  application:
    name: LLMentorLearn_Agent
  ai:
    openai: # openAI配置
      api-key: @dashscope.api.key@
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: qwen-plus
          temperature: 0.7
          maxTokens: 5000
  datasource:
    url: jdbc:mysql://192.168.43.54:3306/llm_mentor?useSSL=false&serverTimezone=UTC
    username: root
    password: 89008900
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1  # 禁用连接池初始化超时检查
  sql:
    init:
      continue-on-error: true  # SQL初始化失败时继续启动

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.ai: DEBUG          # Spring AI 详细日志（关键）
    org.apache.tomcat: INFO
    org.springframework.web: DEBUG           # 打印请求路径、参数
    org.springframework.web.servlet: DEBUG   # 打印 MVC 详细流程


